<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <!-- Windowed exe, avoids Console showing for users. -->
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <ApplicationIcon>Assets/Lumafly.ico</ApplicationIcon>
        <Version>3.3.0.0</Version>
        <UseAppHost>true</UseAppHost>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishTrimmed>true</PublishTrimmed>
        <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
        <!-- Suppress warning because the entire assembly is preserved -->
        <NoWarn>IL2026;IL2057;$(NoWarn)</NoWarn>
    </PropertyGroup>
    
    <!-- Avalonia Files -->
    <ItemGroup>
        <Compile Update="**\**\*.xaml.cs">
            <DependentUpon>%(Filename)</DependentUpon>
        </Compile>
        <AvaloniaResource Include="**\**\*.xaml">
            <SubType>Designer</SubType>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\**" />
        <Compile Update="Views\Windows\ReadmePopup.axaml.cs">
            <DependentUpon>ReadmePopup.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
        <PackageReference Include="Avalonia.Skia" Version="12.1.2" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.2" />
        <PackageReference Include="Deadpikle.AvaloniaProgressRing" Version="0.11.0" />
        <PackageReference Include="HPackage.Net" Version="1.0.1" />
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="Markdown.Avalonia" Version="12.0.0-a3" />
        <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="Mono.Cecil" Version="0.11.6" />
        <PackageReference Include="NetSparkleUpdater.SparkleUpdater" Version="3.1.0" />
        <PackageReference Include="NetSparkleUpdater.UI.Avalonia" Version="4.0.0-preview20260505001" />
        <PackageReference Include="PropertyChanged.SourceGenerator" Version="1.1.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ReactiveUI.Avalonia" Version="12.1.1" />
        <PackageReference Include="Splat.Microsoft.Extensions.DependencyInjection" Version="21.0.0" />
        <PackageReference Include="System.IO.Abstractions" Version="22.2.0" />
        <PackageReference Include="System.Reactive" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="Lumafly" />
    </ItemGroup>

    
    <!-- Localizations -->
    <ItemGroup>
        <!-- ManifestResourceName is required when you want to move resx file to another folder -->
        <EmbeddedResource Update="Localizations\*.resx">
            <ManifestResourceName>$(TargetName).%(Filename)</ManifestResourceName>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <Compile Update="resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <Compile Update="Views\Controls\ExcludableCheckBox.axaml.cs">
          <DependentUpon>ExcludableCheckBox.axaml</DependentUpon>
        </Compile>
    </ItemGroup>
</Project>
