//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumafly {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lumafly.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ,  的本地化字符串。
        /// </summary>
        internal static string Array_Sep {
            get {
                return ResourceManager.GetString("Array_Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available Mods 的本地化字符串。
        /// </summary>
        internal static string AvailableMods {
            get {
                return ResourceManager.GetString("AvailableMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available Packs: 的本地化字符串。
        /// </summary>
        internal static string AvailablePacks {
            get {
                return ResourceManager.GetString("AvailablePacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Mod 的本地化字符串。
        /// </summary>
        internal static string DisableMod {
            get {
                return ResourceManager.GetString("DisableMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Details 的本地化字符串。
        /// </summary>
        internal static string EditDetails {
            get {
                return ResourceManager.GetString("EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Mods 的本地化字符串。
        /// </summary>
        internal static string EditMods {
            get {
                return ResourceManager.GetString("EditMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Pack 的本地化字符串。
        /// </summary>
        internal static string EditPack {
            get {
                return ResourceManager.GetString("EditPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Mod 的本地化字符串。
        /// </summary>
        internal static string EnableMod {
            get {
                return ResourceManager.GetString("EnableMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Sharing Code: 的本地化字符串。
        /// </summary>
        internal static string EnterSharingCode {
            get {
                return ResourceManager.GetString("EnterSharingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t use latest modlinks version. Instead use current version 的本地化字符串。
        /// </summary>
        internal static string FixedVersion_Tooltip {
            get {
                return ResourceManager.GetString("FixedVersion_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load without replacing 的本地化字符串。
        /// </summary>
        internal static string LoadPackAdditive {
            get {
                return ResourceManager.GetString("LoadPackAdditive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load this pack without replacing mods in current mods folder 的本地化字符串。
        /// </summary>
        internal static string LoadPackAdditive_Explanation {
            get {
                return ResourceManager.GetString("LoadPackAdditive_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall 的本地化字符串。
        /// </summary>
        internal static string MI_InstallText_Installed {
            get {
                return ResourceManager.GetString("MI_InstallText_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        internal static string MI_InstallText_NotInstalled {
            get {
                return ResourceManager.GetString("MI_InstallText_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable API 的本地化字符串。
        /// </summary>
        internal static string MLVM_ApiButtonText_DisableAPI {
            get {
                return ResourceManager.GetString("MLVM_ApiButtonText_DisableAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable API 的本地化字符串。
        /// </summary>
        internal static string MLVM_ApiButtonText_EnableAPI {
            get {
                return ResourceManager.GetString("MLVM_ApiButtonText_EnableAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle API 的本地化字符串。
        /// </summary>
        internal static string MLVM_ApiButtonText_ToggleAPI {
            get {
                return ResourceManager.GetString("MLVM_ApiButtonText_ToggleAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The download hash for {0} ({1}) didn&apos;t match the given signature ({2}). It is either corrupt or the entry is incorrect. 的本地化字符串。
        /// </summary>
        internal static string MLVM_DisplayHashMismatch_Msgbox_Text {
            get {
                return ResourceManager.GetString("MLVM_DisplayHashMismatch_Msgbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash mismatch! 的本地化字符串。
        /// </summary>
        internal static string MLVM_DisplayHashMismatch_Msgbox_Title {
            get {
                return ResourceManager.GetString("MLVM_DisplayHashMismatch_Msgbox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to download {0}! The site may be down or you may lack network connectivity. 的本地化字符串。
        /// </summary>
        internal static string MLVM_DisplayNetworkError_Msgbox_Text {
            get {
                return ResourceManager.GetString("MLVM_DisplayNetworkError_Msgbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Error 的本地化字符串。
        /// </summary>
        internal static string MLVM_DisplayNetworkError_Msgbox_Title {
            get {
                return ResourceManager.GetString("MLVM_DisplayNetworkError_Msgbox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hollow Knight is open! This may lead to issues when installing mods. Close Hollow Knight? 的本地化字符串。
        /// </summary>
        internal static string MLVM_InternalUpdateInstallAsync_Msgbox_W_Text {
            get {
                return ResourceManager.GetString("MLVM_InternalUpdateInstallAsync_Msgbox_W_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning! 的本地化字符串。
        /// </summary>
        internal static string MLVM_InternalUpdateInstallAsync_Msgbox_W_Title {
            get {
                return ResourceManager.GetString("MLVM_InternalUpdateInstallAsync_Msgbox_W_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the mod dll or zip 的本地化字符串。
        /// </summary>
        internal static string MLVM_Select_Mod {
            get {
                return ResourceManager.GetString("MLVM_Select_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boss 的本地化字符串。
        /// </summary>
        internal static string ModLinks_Tags_Boss {
            get {
                return ResourceManager.GetString("ModLinks_Tags_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cosmetic 的本地化字符串。
        /// </summary>
        internal static string ModLinks_Tags_Cosmetic {
            get {
                return ResourceManager.GetString("ModLinks_Tags_Cosmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expansion 的本地化字符串。
        /// </summary>
        internal static string ModLinks_Tags_Expansion {
            get {
                return ResourceManager.GetString("ModLinks_Tags_Expansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gameplay 的本地化字符串。
        /// </summary>
        internal static string ModLinks_Tags_Gameplay {
            get {
                return ResourceManager.GetString("ModLinks_Tags_Gameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library 的本地化字符串。
        /// </summary>
        internal static string ModLinks_Tags_Library {
            get {
                return ResourceManager.GetString("ModLinks_Tags_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untagged 的本地化字符串。
        /// </summary>
        internal static string ModLinks_Tags_Untagged {
            get {
                return ResourceManager.GetString("ModLinks_Tags_Untagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Utility 的本地化字符串。
        /// </summary>
        internal static string ModLinks_Tags_Utility {
            get {
                return ResourceManager.GetString("ModLinks_Tags_Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use latest modlinks version 的本地化字符串。
        /// </summary>
        internal static string ModlinksVersion_Tooltip {
            get {
                return ResourceManager.GetString("ModlinksVersion_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning! Are you sure you want to do this? 的本地化字符串。
        /// </summary>
        internal static string MVVM_AreYouSure {
            get {
                return ResourceManager.GetString("MVVM_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is required for {1} to function properly. Do you want to install them? 的本地化字符串。
        /// </summary>
        internal static string MVVM_DependenciesNotInstalledWarning_Body {
            get {
                return ResourceManager.GetString("MVVM_DependenciesNotInstalledWarning_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The mod has dependencies that are not installed! 的本地化字符串。
        /// </summary>
        internal static string MVVM_DependenciesNotInstalledWarning_Header {
            get {
                return ResourceManager.GetString("MVVM_DependenciesNotInstalledWarning_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is required for {1} to function properly. Do you still want to continue? 的本地化字符串。
        /// </summary>
        internal static string MVVM_DependentsWarning_Body {
            get {
                return ResourceManager.GetString("MVVM_DependentsWarning_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning! This mod is required for other mods to function! 的本地化字符串。
        /// </summary>
        internal static string MVVM_DependentsWarning_Header {
            get {
                return ResourceManager.GetString("MVVM_DependentsWarning_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Possibly caused by poor or no internet connection. Please check that and try again 的本地化字符串。
        /// </summary>
        internal static string MVVM_DNSError {
            get {
                return ResourceManager.GetString("MVVM_DNSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception occured while {0} {1} 的本地化字符串。
        /// </summary>
        internal static string MVVM_ExceptionOccur {
            get {
                return ResourceManager.GetString("MVVM_ExceptionOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        internal static string MVVM_Install {
            get {
                return ResourceManager.GetString("MVVM_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to launch lumafly in offline mode? 的本地化字符串。
        /// </summary>
        internal static string MVVM_LaunchOfflineMode {
            get {
                return ResourceManager.GetString("MVVM_LaunchOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetching mods from modlinks... 的本地化字符串。
        /// </summary>
        internal static string MVVM_Loading1 {
            get {
                return ResourceManager.GetString("MVVM_Loading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for response from github... 的本地化字符串。
        /// </summary>
        internal static string MVVM_Loading2 {
            get {
                return ResourceManager.GetString("MVVM_Loading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Still waiting... 的本地化字符串。
        /// </summary>
        internal static string MVVM_Loading3 {
            get {
                return ResourceManager.GetString("MVVM_Loading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying from fallback source... 的本地化字符串。
        /// </summary>
        internal static string MVVM_Loading4 {
            get {
                return ResourceManager.GetString("MVVM_Loading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for response from jsdelivr... 的本地化字符串。
        /// </summary>
        internal static string MVVM_Loading5 {
            get {
                return ResourceManager.GetString("MVVM_Loading5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading the newest mods that are on modlinks... 的本地化字符串。
        /// </summary>
        internal static string MVVM_LoadingWhatsNew {
            get {
                return ResourceManager.GetString("MVVM_LoadingWhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lumafly was unable to load the newest mods from modlinks. 的本地化字符串。
        /// </summary>
        internal static string MVVM_NotAbleToLoadWhatsNew {
            get {
                return ResourceManager.GetString("MVVM_NotAbleToLoadWhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This mod was manually installed and is not from official modlinks 的本地化字符串。
        /// </summary>
        internal static string MVVM_NotInModlinks_Description {
            get {
                return ResourceManager.GetString("MVVM_NotInModlinks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version not from modlinks 的本地化字符串。
        /// </summary>
        internal static string MVVM_NotInModlinks_Disclaimer {
            get {
                return ResourceManager.GetString("MVVM_NotInModlinks_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try running lumafly as an administrator, it may fix the issue 的本地化字符串。
        /// </summary>
        internal static string MVVM_RunAsAdmin {
            get {
                return ResourceManager.GetString("MVVM_RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please make sure to close all other apps that could be using the mods folder 的本地化字符串。
        /// </summary>
        internal static string MVVM_SystemIOException_GeneralFileLock {
            get {
                return ResourceManager.GetString("MVVM_SystemIOException_GeneralFileLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lumafly was unable to access the file in the mods folder 的本地化字符串。
        /// </summary>
        internal static string MVVM_SystemIOException_GeneralReason {
            get {
                return ResourceManager.GetString("MVVM_SystemIOException_GeneralReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please close the following processes as they are locking important files: 的本地化字符串。
        /// </summary>
        internal static string MVVM_SystemIOException_LockingProcessesList {
            get {
                return ResourceManager.GetString("MVVM_SystemIOException_LockingProcessesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lumafly cannot access the file: 的本地化字符串。
        /// </summary>
        internal static string MVVM_SystemIOException_LumaflyCantAccessFile {
            get {
                return ResourceManager.GetString("MVVM_SystemIOException_LumaflyCantAccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please make sure that the mods folder is not in a write protected location 的本地化字符串。
        /// </summary>
        internal static string MVVM_SystemIOException_ProtectedLocation {
            get {
                return ResourceManager.GetString("MVVM_SystemIOException_ProtectedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get modlinks 的本地化字符串。
        /// </summary>
        internal static string MVVM_UnableToGetModlinks {
            get {
                return ResourceManager.GetString("MVVM_UnableToGetModlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected Hollow Knight install at {0}. Is this correct? 的本地化字符串。
        /// </summary>
        internal static string MWVM_DetectedPath_Message {
            get {
                return ResourceManager.GetString("MWVM_DetectedPath_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected path! 的本地化字符串。
        /// </summary>
        internal static string MWVM_DetectedPath_Title {
            get {
                return ResourceManager.GetString("MWVM_DetectedPath_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 failed with HTTP error {0} 的本地化字符串。
        /// </summary>
        internal static string MWVM_Impl_Error_Fetch_ModLinks_Error {
            get {
                return ResourceManager.GetString("MWVM_Impl_Error_Fetch_ModLinks_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get list of mods from modlinks, the operation {0} 的本地化字符串。
        /// </summary>
        internal static string MWVM_Impl_Error_Fetch_ModLinks_Msgbox_Text {
            get {
                return ResourceManager.GetString("MWVM_Impl_Error_Fetch_ModLinks_Msgbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error! 的本地化字符串。
        /// </summary>
        internal static string MWVM_Impl_Error_Fetch_ModLinks_Msgbox_Title {
            get {
                return ResourceManager.GetString("MWVM_Impl_Error_Fetch_ModLinks_Msgbox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 timed out. Please check your internet connection and try again 的本地化字符串。
        /// </summary>
        internal static string MWVM_Impl_Error_Fetch_ModLinks_Timeout {
            get {
                return ResourceManager.GetString("MWVM_Impl_Error_Fetch_ModLinks_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string MWVM_Info {
            get {
                return ResourceManager.GetString("MWVM_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The saved Hollow Knight path is invalid, please re-select a valid path. 的本地化字符串。
        /// </summary>
        internal static string MWVM_InvalidSavedPath_Message {
            get {
                return ResourceManager.GetString("MWVM_InvalidSavedPath_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue anyways. 的本地化字符串。
        /// </summary>
        internal static string MWVM_OutOfDate_ContinueAnyways {
            get {
                return ResourceManager.GetString("MWVM_OutOfDate_ContinueAnyways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the latest release 的本地化字符串。
        /// </summary>
        internal static string MWVM_OutOfDate_GetLatest {
            get {
                return ResourceManager.GetString("MWVM_OutOfDate_GetLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lumafly has a new update available. Please download the newest update (v{0}) to get the latest bug fixes and features. 的本地化字符串。
        /// </summary>
        internal static string MWVM_OutOfDate_Message {
            get {
                return ResourceManager.GetString("MWVM_OutOfDate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out of date! 的本地化字符串。
        /// </summary>
        internal static string MWVM_OutOfDate_Title {
            get {
                return ResourceManager.GetString("MWVM_OutOfDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to detect your Hollow Knight installation. Please select it. 的本地化字符串。
        /// </summary>
        internal static string MWVM_UnableToDetect_Message {
            get {
                return ResourceManager.GetString("MWVM_UnableToDetect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lumafly failed to download update automatically. Lumafly will now open the link to get the latest version 的本地化字符串。
        /// </summary>
        internal static string MWVM_UpdateDownloadError_Message {
            get {
                return ResourceManager.GetString("MWVM_UpdateDownloadError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string MWVM_Warning {
            get {
                return ResourceManager.GetString("MWVM_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Description 的本地化字符串。
        /// </summary>
        internal static string PackDescription {
            get {
                return ResourceManager.GetString("PackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Details 的本地化字符串。
        /// </summary>
        internal static string PackDetails {
            get {
                return ResourceManager.GetString("PackDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit the details of your pack here. 的本地化字符串。
        /// </summary>
        internal static string PackDetails_Explanation {
            get {
                return ResourceManager.GetString("PackDetails_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Name 的本地化字符串。
        /// </summary>
        internal static string PackName {
            get {
                return ResourceManager.GetString("PackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some mods in the pack are outdated, do you want to update them? 的本地化字符串。
        /// </summary>
        internal static string PackUpdatePrompt {
            get {
                return ResourceManager.GetString("PackUpdatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing Managed folder or Assembly-CSharp! 的本地化字符串。
        /// </summary>
        internal static string PU_InvalidApp {
            get {
                return ResourceManager.GetString("PU_InvalidApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Hollow Knight app! 的本地化字符串。
        /// </summary>
        internal static string PU_InvalidAppHeader {
            get {
                return ResourceManager.GetString("PU_InvalidAppHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Hollow Knight exe! Please select the hollow knight exe or its shortcut 的本地化字符串。
        /// </summary>
        internal static string PU_InvalidExeHeader {
            get {
                return ResourceManager.GetString("PU_InvalidExeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the folder containing hollow_knight_Data or Hollow Knight_Data. 的本地化字符串。
        /// </summary>
        internal static string PU_InvalidPath {
            get {
                return ResourceManager.GetString("PU_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Hollow Knight path! 的本地化字符串。
        /// </summary>
        internal static string PU_InvalidPathHeader {
            get {
                return ResourceManager.GetString("PU_InvalidPathHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string PU_InvalidPathTitle {
            get {
                return ResourceManager.GetString("PU_InvalidPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No path was selected! 的本地化字符串。
        /// </summary>
        internal static string PU_NoSelect {
            get {
                return ResourceManager.GetString("PU_NoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No application was selected! 的本地化字符串。
        /// </summary>
        internal static string PU_NoSelectMac {
            get {
                return ResourceManager.GetString("PU_NoSelectMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select your Hollow Knight app. 的本地化字符串。
        /// </summary>
        internal static string PU_SelectApp {
            get {
                return ResourceManager.GetString("PU_SelectApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select your Hollow Knight executable or its shortcut. 的本地化字符串。
        /// </summary>
        internal static string PU_SelectEXE {
            get {
                return ResourceManager.GetString("PU_SelectEXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select your Hollow Knight folder. 的本地化字符串。
        /// </summary>
        internal static string PU_SelectPath {
            get {
                return ResourceManager.GetString("PU_SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Revert to previous mods 的本地化字符串。
        /// </summary>
        internal static string RevertToPreviousMods {
            get {
                return ResourceManager.GetString("RevertToPreviousMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Mods 的本地化字符串。
        /// </summary>
        internal static string SelectedMods {
            get {
                return ResourceManager.GetString("SelectedMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable/Disable the Modding API, the modification to the game files that allow mods to run 的本地化字符串。
        /// </summary>
        internal static string ToggleAPI_Explanation {
            get {
                return ResourceManager.GetString("ToggleAPI_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Fixed Version 的本地化字符串。
        /// </summary>
        internal static string UseFixedVersion {
            get {
                return ResourceManager.GetString("UseFixedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Modlinks Version 的本地化字符串。
        /// </summary>
        internal static string UseModlinksVersion {
            get {
                return ResourceManager.GetString("UseModlinksVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Readme 的本地化字符串。
        /// </summary>
        internal static string ViewReadme {
            get {
                return ResourceManager.GetString("ViewReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ask 的本地化字符串。
        /// </summary>
        internal static string XAML_Ask {
            get {
                return ResourceManager.GetString("XAML_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ask for help 的本地化字符串。
        /// </summary>
        internal static string XAML_AskForHelp {
            get {
                return ResourceManager.GetString("XAML_AskForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authors: 的本地化字符串。
        /// </summary>
        internal static string XAML_Authors {
            get {
                return ResourceManager.GetString("XAML_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically Remove Unused Dependencies 的本地化字符串。
        /// </summary>
        internal static string XAML_AutoRemoveDeps {
            get {
                return ResourceManager.GetString("XAML_AutoRemoveDeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Uses extra {0} of storage) 的本地化字符串。
        /// </summary>
        internal static string XAML_CacheDownloads_Explanation {
            get {
                return ResourceManager.GetString("XAML_CacheDownloads_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Path 的本地化字符串。
        /// </summary>
        internal static string XAML_ChangPath {
            get {
                return ResourceManager.GetString("XAML_ChangPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check For Updates 的本地化字符串。
        /// </summary>
        internal static string XAML_CheckForUpdates {
            get {
                return ResourceManager.GetString("XAML_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select manually 的本地化字符串。
        /// </summary>
        internal static string XAML_ChooseDependenciesToUninstall {
            get {
                return ResourceManager.GetString("XAML_ChooseDependenciesToUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Error 的本地化字符串。
        /// </summary>
        internal static string XAML_CopyError {
            get {
                return ResourceManager.GetString("XAML_CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new pack 的本地化字符串。
        /// </summary>
        internal static string XAML_CreateNewPack {
            get {
                return ResourceManager.GetString("XAML_CreateNewPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normally Lumafly loads its list of mods from the official modlinks. If you want to load your own then enter its URI here it accepts https links or files (in the format file://{filepath}). \nEmpty links or invalid links will load official modlinks 的本地化字符串。
        /// </summary>
        internal static string XAML_CustomModlinksExplanation {
            get {
                return ResourceManager.GetString("XAML_CustomModlinksExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter link to custom modlinks. Needs a reload to take effect 的本地化字符串。
        /// </summary>
        internal static string XAML_CustomModlinksWatermark {
            get {
                return ResourceManager.GetString("XAML_CustomModlinksWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete pack 的本地化字符串。
        /// </summary>
        internal static string XAML_DeletePack {
            get {
                return ResourceManager.GetString("XAML_DeletePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependencies: 的本地化字符串。
        /// </summary>
        internal static string XAML_Dependencies {
            get {
                return ResourceManager.GetString("XAML_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        internal static string XAML_Description {
            get {
                return ResourceManager.GetString("XAML_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable All 的本地化字符串。
        /// </summary>
        internal static string XAML_Disable_All_Installed {
            get {
                return ResourceManager.GetString("XAML_Disable_All_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        internal static string XAML_Donate {
            get {
                return ResourceManager.GetString("XAML_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit pack 的本地化字符串。
        /// </summary>
        internal static string XAML_EditPack {
            get {
                return ResourceManager.GetString("XAML_EditPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit mod&apos;s settings file 的本地化字符串。
        /// </summary>
        internal static string XAML_EditSettings {
            get {
                return ResourceManager.GetString("XAML_EditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable All 的本地化字符串。
        /// </summary>
        internal static string XAML_Enable_All_Installed {
            get {
                return ResourceManager.GetString("XAML_Enable_All_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exact Search 的本地化字符串。
        /// </summary>
        internal static string XAML_Exact_Search {
            get {
                return ResourceManager.GetString("XAML_Exact_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Mods:   的本地化字符串。
        /// </summary>
        internal static string XAML_FilterMods {
            get {
                return ResourceManager.GetString("XAML_FilterMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Path 的本地化字符串。
        /// </summary>
        internal static string XAML_GamePath {
            get {
                return ResourceManager.GetString("XAML_GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate a 8 digit sharing code. This can be given to someone else and they can use this pack 的本地化字符串。
        /// </summary>
        internal static string XAML_GenerateSharingCode {
            get {
                return ResourceManager.GetString("XAML_GenerateSharingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter format to github mirror. Needs a reload to take effect 的本地化字符串。
        /// </summary>
        internal static string XAML_GithubMirrorFormatWatermark {
            get {
                return ResourceManager.GetString("XAML_GithubMirrorFormatWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import pack 的本地化字符串。
        /// </summary>
        internal static string XAML_ImportPack {
            get {
                return ResourceManager.GetString("XAML_ImportPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string XAML_Info {
            get {
                return ResourceManager.GetString("XAML_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lumafly is an installer for Hollow Knight version 1.5. It will not work for older versions of Hollow Knight. 的本地化字符串。
        /// </summary>
        internal static string XAML_InfoBody {
            get {
                return ResourceManager.GetString("XAML_InfoBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discord 的本地化字符串。
        /// </summary>
        internal static string XAML_InfoLinkDiscord {
            get {
                return ResourceManager.GetString("XAML_InfoLinkDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github\n 的本地化字符串。
        /// </summary>
        internal static string XAML_InfoLinkGithub {
            get {
                return ResourceManager.GetString("XAML_InfoLinkGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HK Mod\nManager 的本地化字符串。
        /// </summary>
        internal static string XAML_InfoLinkHKMM {
            get {
                return ResourceManager.GetString("XAML_InfoLinkHKMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An Alternate Installer 的本地化字符串。
        /// </summary>
        internal static string XAML_InfoLinkHKMMToolTip {
            get {
                return ResourceManager.GetString("XAML_InfoLinkHKMMToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Mods\n 的本地化字符串。
        /// </summary>
        internal static string XAML_InfoLinkModdingDocs {
            get {
                return ResourceManager.GetString("XAML_InfoLinkModdingDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Readme\n 的本地化字符串。
        /// </summary>
        internal static string XAML_InfoLinkReadme {
            get {
                return ResourceManager.GetString("XAML_InfoLinkReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relevant Links 的本地化字符串。
        /// </summary>
        internal static string XAML_InfoLinksHeader {
            get {
                return ResourceManager.GetString("XAML_InfoLinksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modding\nTutorial 的本地化字符串。
        /// </summary>
        internal static string XAML_InfoLinkTutorial {
            get {
                return ResourceManager.GetString("XAML_InfoLinkTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Website\n 的本地化字符串。
        /// </summary>
        internal static string XAML_InfoLinkWebsite {
            get {
                return ResourceManager.GetString("XAML_InfoLinkWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integrations: 的本地化字符串。
        /// </summary>
        internal static string XAML_Integrations {
            get {
                return ResourceManager.GetString("XAML_Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string XAML_Language {
            get {
                return ResourceManager.GetString("XAML_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Month 的本地化字符串。
        /// </summary>
        internal static string XAML_LastMonth {
            get {
                return ResourceManager.GetString("XAML_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Week 的本地化字符串。
        /// </summary>
        internal static string XAML_LastWeek {
            get {
                return ResourceManager.GetString("XAML_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Modded Game 的本地化字符串。
        /// </summary>
        internal static string XAML_LaunchModded {
            get {
                return ResourceManager.GetString("XAML_LaunchModded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Vanilla Game 的本地化字符串。
        /// </summary>
        internal static string XAML_LaunchVanilla {
            get {
                return ResourceManager.GetString("XAML_LaunchVanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Pack 的本地化字符串。
        /// </summary>
        internal static string XAML_LoadPack {
            get {
                return ResourceManager.GetString("XAML_LoadPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low Storage Mode 的本地化字符串。
        /// </summary>
        internal static string XAML_Low_Storage_Mode {
            get {
                return ResourceManager.GetString("XAML_Low_Storage_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manually Install 的本地化字符串。
        /// </summary>
        internal static string XAML_Manual_Install {
            get {
                return ResourceManager.GetString("XAML_Manual_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: they may be used by any mods you have installed manually 的本地化字符串。
        /// </summary>
        internal static string XAML_ManuallyInstalledModesNote {
            get {
                return ResourceManager.GetString("XAML_ManuallyInstalledModesNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mods 的本地化字符串。
        /// </summary>
        internal static string XAML_Mods {
            get {
                return ResourceManager.GetString("XAML_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string XAML_ModsFilter_All {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        internal static string XAML_ModsFilter_Enabled {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installed 的本地化字符串。
        /// </summary>
        internal static string XAML_ModsFilter_Installed {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out of date 的本地化字符串。
        /// </summary>
        internal static string XAML_ModsFilter_OutOfDate {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_OutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update All 的本地化字符串。
        /// </summary>
        internal static string XAML_ModsFilter_OutOfDate_Update {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_OutOfDate_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whats New 的本地化字符串。
        /// </summary>
        internal static string XAML_ModsFilter_WhatsNew {
            get {
                return ResourceManager.GetString("XAML_ModsFilter_WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mods In Pack: 的本地化字符串。
        /// </summary>
        internal static string XAML_ModsInPack {
            get {
                return ResourceManager.GetString("XAML_ModsInPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Mods 的本地化字符串。
        /// </summary>
        internal static string XAML_NewMods {
            get {
                return ResourceManager.GetString("XAML_NewMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No mods to display 的本地化字符串。
        /// </summary>
        internal static string XAML_No_Items {
            get {
                return ResourceManager.GetString("XAML_No_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string XAML_None {
            get {
                return ResourceManager.GetString("XAML_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal Search 的本地化字符串。
        /// </summary>
        internal static string XAML_Normal_Search {
            get {
                return ResourceManager.GetString("XAML_Normal_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string XAML_Off {
            get {
                return ResourceManager.GetString("XAML_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        internal static string XAML_Ok {
            get {
                return ResourceManager.GetString("XAML_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string XAML_On {
            get {
                return ResourceManager.GetString("XAML_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bulk Actions 的本地化字符串。
        /// </summary>
        internal static string XAML_Open_Bulk_Action {
            get {
                return ResourceManager.GetString("XAML_Open_Bulk_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open folder where this mod is installed 的本地化字符串。
        /// </summary>
        internal static string XAML_OpenFolder {
            get {
                return ResourceManager.GetString("XAML_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait launching game... 的本地化字符串。
        /// </summary>
        internal static string XAML_OpeningGame {
            get {
                return ResourceManager.GetString("XAML_OpeningGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Logs Folder 的本地化字符串。
        /// </summary>
        internal static string XAML_OpenLogsFolder {
            get {
                return ResourceManager.GetString("XAML_OpenLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Mods Folder 的本地化字符串。
        /// </summary>
        internal static string XAML_OpenMods {
            get {
                return ResourceManager.GetString("XAML_OpenMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Folder 的本地化字符串。
        /// </summary>
        internal static string XAML_OpenModsOrSaves {
            get {
                return ResourceManager.GetString("XAML_OpenModsOrSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packs 的本地化字符串。
        /// </summary>
        internal static string XAML_Packs {
            get {
                return ResourceManager.GetString("XAML_Packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin 的本地化字符串。
        /// </summary>
        internal static string XAML_Pin {
            get {
                return ResourceManager.GetString("XAML_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin a mod so it isn&apos;t automatically replaced by Lumafly 的本地化字符串。
        /// </summary>
        internal static string XAML_PinMod_Explanation {
            get {
                return ResourceManager.GetString("XAML_PinMod_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record as custom version 的本地化字符串。
        /// </summary>
        internal static string XAML_RegisterNotInModlinks {
            get {
                return ResourceManager.GetString("XAML_RegisterNotInModlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record this mod&apos;s version as not from modlinks. Doesn&apos;t affect the mod in any way only affects how lumafly handles it. A pinned custom version mod will never be replaced by lumafly 的本地化字符串。
        /// </summary>
        internal static string XAML_RegisterNotInModlinks_Explanation {
            get {
                return ResourceManager.GetString("XAML_RegisterNotInModlinks_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload Lumafly 的本地化字符串。
        /// </summary>
        internal static string XAML_ReloadLumafly {
            get {
                return ResourceManager.GetString("XAML_ReloadLumafly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Reload for changes to take effect) 的本地化字符串。
        /// </summary>
        internal static string XAML_ReloadPrompt {
            get {
                return ResourceManager.GetString("XAML_ReloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report a bug or an issue with this mod 的本地化字符串。
        /// </summary>
        internal static string XAML_ReportBug {
            get {
                return ResourceManager.GetString("XAML_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Error 的本地化字符串。
        /// </summary>
        internal static string XAML_ReportError {
            get {
                return ResourceManager.GetString("XAML_ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository 的本地化字符串。
        /// </summary>
        internal static string XAML_Repository {
            get {
                return ResourceManager.GetString("XAML_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Mod: force re-installs the mod and removes its persistent settings 的本地化字符串。
        /// </summary>
        internal static string XAML_ResetMod {
            get {
                return ResourceManager.GetString("XAML_ResetMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Saves Folder 的本地化字符串。
        /// </summary>
        internal static string XAML_SavesFolder {
            get {
                return ResourceManager.GetString("XAML_SavesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search by Dependencies and Integrations 的本地化字符串。
        /// </summary>
        internal static string XAML_Search_Dependents {
            get {
                return ResourceManager.GetString("XAML_Search_Dependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search by Integrations 的本地化字符串。
        /// </summary>
        internal static string XAML_Search_Integrations {
            get {
                return ResourceManager.GetString("XAML_Search_Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Search 的本地化字符串。
        /// </summary>
        internal static string XAML_Search_Options {
            get {
                return ResourceManager.GetString("XAML_Search_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Type 的本地化字符串。
        /// </summary>
        internal static string XAML_Search_Type {
            get {
                return ResourceManager.GetString("XAML_Search_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Author 的本地化字符串。
        /// </summary>
        internal static string XAML_SearchAuthor {
            get {
                return ResourceManager.GetString("XAML_SearchAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Search 的本地化字符串。
        /// </summary>
        internal static string XAML_SearchMark {
            get {
                return ResourceManager.GetString("XAML_SearchMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Authors 的本地化字符串。
        /// </summary>
        internal static string XAML_Select_Authors {
            get {
                return ResourceManager.GetString("XAML_Select_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Mod 的本地化字符串。
        /// </summary>
        internal static string XAML_Select_Mod {
            get {
                return ResourceManager.GetString("XAML_Select_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Tags 的本地化字符串。
        /// </summary>
        internal static string XAML_Select_Tags {
            get {
                return ResourceManager.GetString("XAML_Select_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string XAML_Settings {
            get {
                return ResourceManager.GetString("XAML_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the shareable download link of this mod. 的本地化字符串。
        /// </summary>
        internal static string XAML_Share {
            get {
                return ResourceManager.GetString("XAML_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share this pack 的本地化字符串。
        /// </summary>
        internal static string XAML_SharePack {
            get {
                return ResourceManager.GetString("XAML_SharePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share this pack as a zip file. You will need to send this zip file yourself. 的本地化字符串。
        /// </summary>
        internal static string XAML_SharePackManually {
            get {
                return ResourceManager.GetString("XAML_SharePackManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sharing Code: 的本地化字符串。
        /// </summary>
        internal static string XAML_SharingCode {
            get {
                return ResourceManager.GetString("XAML_SharingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to show full error 的本地化字符串。
        /// </summary>
        internal static string XAML_ShowError {
            get {
                return ResourceManager.GetString("XAML_ShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags: 的本地化字符串。
        /// </summary>
        internal static string XAML_Tags {
            get {
                return ResourceManager.GetString("XAML_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle All 的本地化字符串。
        /// </summary>
        internal static string XAML_Toggle_All {
            get {
                return ResourceManager.GetString("XAML_Toggle_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable all mods if any are enabled, Enable all mods if all are disabled 的本地化字符串。
        /// </summary>
        internal static string XAML_Toggle_All_Tooltip {
            get {
                return ResourceManager.GetString("XAML_Toggle_All_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall All 的本地化字符串。
        /// </summary>
        internal static string XAML_Uninstall_All {
            get {
                return ResourceManager.GetString("XAML_Uninstall_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstalling this mod will leave dependencies that appear to be unused now 的本地化字符串。
        /// </summary>
        internal static string XAML_UninstallDependencies {
            get {
                return ResourceManager.GetString("XAML_UninstallDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto remove dependencies? 的本地化字符串。
        /// </summary>
        internal static string XAML_UninstallDependencies_Title {
            get {
                return ResourceManager.GetString("XAML_UninstallDependencies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpin 的本地化字符串。
        /// </summary>
        internal static string XAML_Unpin {
            get {
                return ResourceManager.GetString("XAML_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string XAML_Update {
            get {
                return ResourceManager.GetString("XAML_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update API 的本地化字符串。
        /// </summary>
        internal static string XAML_UpdateAPI {
            get {
                return ResourceManager.GetString("XAML_UpdateAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated Mods 的本地化字符串。
        /// </summary>
        internal static string XAML_UpdatedMods {
            get {
                return ResourceManager.GetString("XAML_UpdatedMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Custom Modlinks 的本地化字符串。
        /// </summary>
        internal static string XAML_UseCustomModlinks {
            get {
                return ResourceManager.GetString("XAML_UseCustomModlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Github Mirror 的本地化字符串。
        /// </summary>
        internal static string XAML_UseGithubMirror {
            get {
                return ResourceManager.GetString("XAML_UseGithubMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        internal static string XAML_Version {
            get {
                return ResourceManager.GetString("XAML_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warn before removing a dependent mod 的本地化字符串。
        /// </summary>
        internal static string XAML_WarnBeforeRemovingDependentMods {
            get {
                return ResourceManager.GetString("XAML_WarnBeforeRemovingDependentMods", resourceCulture);
            }
        }
    }
}
