name: Test and Build

on: [push, pull_request]

jobs:

  tests:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Test
      run: dotnet test
      
  build-windows:
    runs-on: windows-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore -r win-x64
    - name: Build
      run: |
        cd Scarab
        dotnet publish --no-restore -r win-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=embedded
        cd ..
    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: Scarab-Windows
        path: Scarab/bin/Release/net7.0/win-x64/publish/

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore -r linux-x64
    - name: Build
      run: | 
        cd Scarab
        dotnet publish -r linux-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
        cd ..
    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: Scarab-Linux
        path: Scarab/bin/Release/net7.0/linux-x64/publish/

  build-macos:
    runs-on: macos-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore -r osx-x64
    - name: Build
      run: |
        cd Scarab
        dotnet publish --no-restore -r osx-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
        cd ..
        mkdir out
        python3 make_app.py Scarab.app Scarab/bin/Release/net7.0/osx-x64/publish
    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: Scarab-MacOS
        path: out/mac.zip

  release:
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with: 
          path: ./artifacts

      - name: Zip
        run: |
          zip -jr Scarab-Windows.zip ./artifacts/Scarab-Windows/*
          
          chmod +x ./artifacts/Scarab-Linux/Scarab
          zip -jr Scarab-Linux.zip ./artifacts/Scarab-Linux/*
          
          mv ./artifacts/Scarab-MacOS/mac.zip Scarab-MacOS.zip

      - name: Create release if a new tag is pushed
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./Scarab-Windows.zip
            ./Scarab-MacOS.zip
            ./Scarab-Linux.zip
